config/routes.rb
Rails.application.routes.draw do


  resources :facts

  resources :banners, except: [:show]
  mount Ckeditor::Engine => '/ckeditor'
  resources :events do
    collection do
      get 'search'
    end
    resources :eventscomments
    member do
      put "like", to: "events#upvote"
      put "dislike", to: "events#downvote"

    end
  end
  devise_for :bloggers
  resources :projects
  resources :abouts
  resources :bloggers, only: [:index, :update]
  resources :videos do
    collection do
      get 'search'
    end
    member do
      put "like", to: "videos#upvote"
      put "dislike", to: "videos#downvote"
    end
  end
  resources :homes
  resources :musics do
    collection do
      get 'search'

    end
    resources :musiccomments
    member do
      put "like", to: "musics#upvote"
      put "dislike", to: "musics#downvote"
      get 'download', to: "musics#download"
    end
    end
  root 'welcome#index'
  resource :bloggers
  get '/you',           :to => 'bloggers#show',    :as => :you
  get '/you/update',    :to => 'bloggers#update',  :as => :you_update

  get '/soundcloud/connect',    :to => 'soundcloud#connect',    :as => :soundcloud_connect
  get '/soundcloud/connected',  :to => 'soundcloud#connected',  :as => :soundcloud_connected
  get '/soundcloud/disconnect', :to => 'soundcloud#disconnect', :as => :soundcloud_disconnect

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  has_attached_file :thumbnail, styles: { large: "1200x1000#", medium: "600x500#" }
  
validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/
end

app/models/banner.rb
class Banner < ApplicationRecord
  has_attached_file :thumbnail, styles: { large: "1200x1000#", medium: "600x500#" }

validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/
end

app/models/blogger.rb
class Blogger < ApplicationRecord
  has_attached_file :thumbnail, styles: { large: "1200x1000#", medium: "600x500#" }
validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 
end

app/models/event.rb
class Event < ApplicationRecord
  acts_as_votable
  searchkick
  has_attached_file :thumbnail

validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/

has_many :eventscomments, dependent: :destroy
end

app/models/eventscomment.rb
class Eventscomment < ApplicationRecord
  belongs_to :event
end

app/models/fact.rb
class Fact < ApplicationRecord
  has_attached_file :thumbnail

validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/
end

app/models/home.rb
class Home < ApplicationRecord
  has_attached_file :thumbnail, styles: { large: "1200x1000#", medium: "600x500#" }
validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/

end

app/models/music.rb
class Music < ApplicationRecord
  acts_as_votable
    searchkick
    #currently use this function for search. (It works)
    scope :searching, ->(query) { __elasticsearch__.search(query).records }
  has_attached_file :albumimage, default_url: "/images/:style/missing.png"
validates_attachment_content_type :albumimage, content_type: /\Aimage\/.*\z/

has_attached_file :song
validates_attachment_content_type :song,
content_type: [
  'application/mp3',
  'application/x-mp3',
  'audio/mpeg',
  ['audio/mpeg'], # note the array around the type
  'audio/mp3'
]

has_many :musiccomments, dependent: :destroy
def self.highest_voted
  self.order("cached_votes_score DESC")
end

end

app/models/musiccomment.rb
class Musiccomment < ApplicationRecord
  belongs_to :music
end

app/models/project.rb
class Project < ApplicationRecord
  has_attached_file :thumbnail, styles: { large: "1200x1000#", medium: "600x500#" }
  
validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/
end

app/models/session.rb
class Session < ApplicationRecord
  acts_as_voter
  
end

app/models/user.rb
class User < ApplicationRecord
  SOUNDCLOUD_CLIENT_ID     = ENV['SOUNDCLOUD_CLIENT_ID']
  SOUNDCLOUD_CLIENT_SECRET = ENV['SOUNDCLOUD_CLIENT_SECRET']

  def self.soundcloud_client(options={})
    options = {
      :client_id     => SOUNDCLOUD_CLIENT_ID,
      :client_secret => SOUNDCLOUD_CLIENT_SECRET,
    }.merge(options)

    Soundcloud.new(options)
  end


  def soundcloud_client(options={})
    options= {
      :expires_at    => soundcloud_expires_at,
      :access_token  => soundcloud_access_token,
      :refresh_token => soundcloud_refresh_token
    }.merge(options)

    client = self.class.soundcloud_client(options)

    # define a callback for successful token exchanges
    # this will make sure that new access_tokens are persisted once an existing
    # access_token expired and a new one was retrieved from the soundcloud api
    client.on_exchange_token do
      self.update_attributes!({
        :soundcloud_access_token  => client.access_token,
        :soundcloud_refresh_token => client.refresh_token,
        :soundcloud_expires_at    => client.expires_at,
      })
    end

    client
  end
end

app/models/video.rb
class Video < ApplicationRecord
  acts_as_votable
  searchkick
  #currently use this function for search. (It works)
  scope :searching, ->(query) { __elasticsearch__.search(query).records }
  def self.highest_voted
    self.all.order("cached_votes_score DESC")
  end

  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i

  validates :link, presence: true, format: YT_LINK_FORMAT

before_create -> do
  uid = link.match(YT_LINK_FORMAT)
  self.uid = uid[2] if uid && uid[2]

  if self.uid.to_s.length != 11
    self.errors.add(:link, 'is invalid.')
    false
  elsif Video.where(uid: self.uid).any?
    self.errors.add(:link, 'is not unique.')
    false
  else
    def get_additional_info
      begin
        client = YouTubeIt::OAuth2Client.new(dev_key: '571999469842-8djhdmjuis4kit4lre6upqsg346j2os3.apps.googleusercontent.com')
        video = client.video_by(uid)
        self.title = video.title
        self.duration = parse_duration(video.duration)
        self.author = video.author.name
        self.thumbnail = video.thumbnail_url
        self.likes = video.rating.likes
        self.dislikes = video.rating.dislikes
      rescue
        self.title = '' ; self.duration = '00:00:00' ; self.author = '' ; self.likes = 0 ; self.dislikes = 0
      end
    end

  end





def parse_duration(d)
  hr = (d / 3600).floor
  min = ((d - (hr * 3600)) / 60).floor
  sec = (d - (hr * 3600) - (min * 60)).floor

  hr = '0' + hr.to_s if hr.to_i < 10
  min = '0' + min.to_s if min.to_i < 10
  sec = '0' + sec.to_s if sec.to_i < 10

  hr.to_s + ':' + min.to_s + ':' + sec.to_s
end
end

end

app/controllers/bloggers_controller.rb
class BloggersController < ApplicationController
  before_action :authenticate_blogger!

  layout "bloggers"

  def index
  end

  def show
    @tracks = current_user.soundcloud_client.get("/me/tracks", :limit => 5)
    @me     = current_user.soundcloud_client.get("/me")
  end

  def update
    res = current_user.soundcloud_client.put("/me", :user => {:description => params[:description]})
    redirect_to :action => :show
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/bloggers_helper.rb
module BloggersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bloggers/_adminbar.html.erb
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
		<form role="search">
			<div class="form-group">
				<input type="text" class="form-control" placeholder="Search">
			</div>
		</form>
		<ul class="nav menu">
			<li><%= link_to new_banner_path do %>
						<%= fa_icon "home" %>
							Home banner
							<% end %>
						</li>

						<li><%= link_to new_music_path do %>
									<%= fa_icon "soundcloud" %>
										New Music Upload
										<% end %></li>

						<li><%= link_to soundcloud_connect_path, :class => "connect"  do %>
								<%= fa_icon "soundcloud" %>
								  Connect With SoundCloud
									<% end %>
								</li>

						<li><%= link_to new_video_path do %>
									<%= fa_icon "youtube" %>
										New Video
										<% end %></li>

						<li><%= link_to new_about_path do %>
									<%= fa_icon "users" %>
										About Us
										<% end %></li>

										<li><%= link_to new_event_path do %>
													<%= fa_icon "newspaper-o" %>
														New Project
														<% end %></li>

										<li><%= link_to new_fact_path do %>
													<%= fa_icon "newspaper-o" %>
														Fun Facts
														<% end %></li>

													

														<li><%= link_to destroy_blogger_session_path, method: :delete do %>
																	<%= fa_icon "sign-out" %>
																		Logout
																		<% end %></li>

		</ul>
	</div><!--/.sidebar-->
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">

app/views/bloggers/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
        <%= link_to "PouRap Admin", root_path, class: "navbar-brand"  %> |

		



				<ul class="user-menu">
					<li class="dropdown pull-right">

						<a href="#" class="dropdown-toggle" data-toggle="dropdown"><svg class="glyph stroked male-user">
							<use xlink:href="#stroked-male-user"></use></svg> blogger  <span class="caret"></span></a>



						<ul class="dropdown-menu" role="menu">
							<li><a href="#"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> Profile</a></li>
              <li><%= link_to  destroy_blogger_session_path, :method => :delete do  %>
                    <svg class="glyph stroked cancel"><use xlink:href="#stroked-cancel"></use></svg>
                    Logout
                    <% end %>
                  </li>


						</ul>
					</li>
				</ul>
			</div>

		</div><!-- /.container-fluid -->
	</nav>

app/views/bloggers/index.html.erb
<%= render "header" %>


<%= render 'adminbar' %>

app/views/bloggers/show.html.erb
<%= render "header" %>


<%= render 'adminbar' %>

<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Soundcloud</h1>
			</div>
		</div><!--/.row-->


		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">Soundcloud dashboard </div>
					<div class="panel-body">
						<div class="col-md-6 col-md-offset-3">
              <div class="infos">
  <div class="details">
    <b>Your SoundCloud User Infos:</b>
    <ul>
      <li>Username: <%= @me.username %></li>
      <li>Fullname: <%= @me.full_name %></li>
      <li>Location: <%= @me.city %>, <%= @me.country %></li>
    </ul>
  </div>
  <%= image_tag(@me.avatar_url, :class => "avatar") %>

</div>

<div class="description">
  <% form_tag you_update_path, :method => "post" do %>
    <b>Description:</b>
    <textarea name="description"><%= @me.description %></textarea>
    <input type="submit" value="update" />
    <span class="warning">this will change your SoundCloud profile description!</span>
  <% end %>
</div>

<div class="tracks">
  <b>Your 5 latest tracks</b>
  <ul>
    <% @tracks.each do |track| %>
      <li><%= link_to track.title, track.permalink_url %></li>
    <% end %>
  </ul>
</div>



</div>
</div>
</div>
</div>
</div>