config/routes.rb
Rails.application.routes.draw do


  resources :facts

  resources :banners, except: [:show]
  mount Ckeditor::Engine => '/ckeditor'
  resources :events do
    collection do
      get 'search'
    end
    resources :eventscomments
    member do
      put "like", to: "events#upvote"
      put "dislike", to: "events#downvote"

    end
  end
  devise_for :bloggers
  resources :projects
  resources :abouts
  resources :bloggers, only: [:index, :update]
  resources :videos do
    collection do
      get 'search'
    end
    member do
      put "like", to: "videos#upvote"
      put "dislike", to: "videos#downvote"
    end
  end
  resources :homes
  resources :musics do
    collection do
      get 'search'

    end
    resources :musiccomments
    member do
      put "like", to: "musics#upvote"
      put "dislike", to: "musics#downvote"
      get 'download', to: "musics#download"
    end
    end
  root 'welcome#index'
  resource :bloggers
  get '/you',           :to => 'bloggers#show',    :as => :you
  get '/you/update',    :to => 'bloggers#update',  :as => :you_update

  get '/soundcloud/connect',    :to => 'soundcloud#connect',    :as => :soundcloud_connect
  get '/soundcloud/connected',  :to => 'soundcloud#connected',  :as => :soundcloud_connected
  get '/soundcloud/disconnect', :to => 'soundcloud#disconnect', :as => :soundcloud_disconnect

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord
  acts_as_votable
  searchkick
  #currently use this function for search. (It works)
  scope :searching, ->(query) { __elasticsearch__.search(query).records }
  def self.highest_voted
    self.all.order("cached_votes_score DESC")
  end

  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i

  validates :link, presence: true, format: YT_LINK_FORMAT

before_create -> do
  uid = link.match(YT_LINK_FORMAT)
  self.uid = uid[2] if uid && uid[2]

  if self.uid.to_s.length != 11
    self.errors.add(:link, 'is invalid.')
    false
  elsif Video.where(uid: self.uid).any?
    self.errors.add(:link, 'is not unique.')
    false
  else
    def get_additional_info
      begin
        client = YouTubeIt::OAuth2Client.new(dev_key: '571999469842-8djhdmjuis4kit4lre6upqsg346j2os3.apps.googleusercontent.com')
        video = client.video_by(uid)
        self.title = video.title
        self.duration = parse_duration(video.duration)
        self.author = video.author.name
        self.thumbnail = video.thumbnail_url
        self.likes = video.rating.likes
        self.dislikes = video.rating.dislikes
      rescue
        self.title = '' ; self.duration = '00:00:00' ; self.author = '' ; self.likes = 0 ; self.dislikes = 0
      end
    end

  end





def parse_duration(d)
  hr = (d / 3600).floor
  min = ((d - (hr * 3600)) / 60).floor
  sec = (d - (hr * 3600) - (min * 60)).floor

  hr = '0' + hr.to_s if hr.to_i < 10
  min = '0' + min.to_s if min.to_i < 10
  sec = '0' + sec.to_s if sec.to_i < 10

  hr.to_s + ':' + min.to_s + ':' + sec.to_s
end
end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_blogger!, except: [:index, :show, :search]
  layout "bloggers", except:[:index, :show, :search]
 before_action :set_about, only: [:show, :destroy]

 def search
   if params[:search].present?
     @videos = Video.search(params[:search])
     @musics = Music.highest_voted.limit(10)
      @videos = Video.highest_voted.limit(10)
      @facts = Fact.all.order('created_at DESC').limit(1)
      @abouts = About.all.order("created_at DESC").limit(1)


    @abouts = About.all.limit(1)

   else
     @videos = Video.all.order("created_at DESC")
   end
 end
  def index
    @videos = Video.all.order('created_at DESC')
    @abouts = About.all.order("created_at DESC").limit(1)
    @videos = Video.highest_voted.all.limit(10)
    @musics = Music.highest_voted.all.limit(10)
    @facts = Fact.all.order('created_at DESC').limit(1)


  end

def show
  @videos = Video.highest_voted.all.limit(10)
  @musics = Music.highest_voted.all.limit(10)
  @facts = Fact.all.order('created_at DESC').limit(1)
    @abouts = About.all.limit(1)

end

  def new
  @video = Video.new
end

def create
@video = Video.new(video_params)
  if @video.save
  flash = { success: "Congratulations!! Video Added Successfully", error: "Action Not Successfull." }
    redirect_to root_url
  else
    render 'new'
  end
end

def destroy
  @video.destroy
  redirect_to videos_url, notice: "video was removed"
end
def upvote
  @video = Video.find(params[:id])
  session[:voting_id] = request.remote_ip
  voter = Session.find_or_create_by(ip: session[:voting_id])
  voter.likes @video
  redirect_to :back
end

def downvote
  @video = Video.find(params[:id])
  session[:voting_id] = request.remote_ip
voter = Session.find_or_create_by(ip: session[:voting_id])
voter.dislikes @video
  redirect_to :back
end


  private
  def set_about
    @video = Video.find(params[:id])
  end


    def video_params
    params.require(:video).permit(:link, :title, :description, :story)
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= simple_form_for(@video, html: { class: 'form-horizontal' }) do |f| %>
<div class="form-group">
<%= f.input :link, class: "form-control", required: true %>

</div>
<div class="form-group">
  <%= f.input :title, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.input :description, class: "form-control", as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' } } %>
</div>
<div class="form-group">
  <%= f.input :story, class: 'form-control', as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' } }, label: "Video Story" %>
</div>

<div class="form-group">
  <%= f.submit :submit, class: "btn btn1" %>
</div>
<% end %>

app/views/videos/index.html.erb
<div class="banner-2">
  <div class="container">
    <div class="col-md-12">
      <div class="wrapper top">
      <%= form_tag search_videos_path, method: :get, role: "search" do  %>
        <%=text_field_tag :search, params[:search], class: "search1", placeholder: "Search" %>
        <%=submit_tag "", name:nil, label: false,  class: "submit1"  %>
        <% end %>
      </div>
      </div>
  </div>
</div>

<div class="technology">
  <div class="container">
    <div class=" col-md-9 technology-left" >
      <div class="w3ls">
        <% @videos.each do |video| %>
        <div class="col-md-6 w3ls-left wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
          <div class="tc-ch">
            <div class="tch-img-video">
              <%= link_to video, target: '_blank' do %>
              <%= image_tag("https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg", alt: video.title,
              class: ' img-responsive ') %>
              <span><%= fa_icon "youtube-play 3x", class: "text-center play" %></span>
              <%end%>
            </div>
            <span>    <h4><%= video.title %></h4></span>


            <div class="bht1">
              <%= link_to "Veiw More ", video %>
              <% if blogger_signed_in? %>
              <%= link_to 'Remove', video_path(video), method: :delete, remote: true,  data: { confirm: 'Are you sure?' }  %>
              <% end %>
            </div>
            <div class="soci">
              <ul>
                <li class="hvr-rectangle-out"><a class="fb" href="#"></a></li>
              </ul>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
        <% end %>
        <div class="clearfix"></div>

      </div>
    </div>
    <%= render "shared/sidebar" %>

  </div>
</div>

app/views/videos/new.html.erb
<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Videos</h1>
			</div>
		</div><!--/.row-->


		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">Add Your video link from youtube </div>
					<div class="panel-body">
						<div class="col-md-6 col-md-offset-3">

              <%= render "form", video: :@video %>


              </div>
              </div>
              </div>
              </div>
              </div>

app/views/videos/search.html.erb
<div class="banner-2">
  <div class="container">
    <div class="col-md-12">
      <div class="wrapper top">
      <%= form_tag search_videos_path, method: :get, role: "search" do  %>
        <%=text_field_tag :search, params[:search], class: "search1", placeholder: "Search" %>
        <%=submit_tag "", name:nil, label: false,  class: "submit1"  %>
        <% end %>
      </div>
      </div>
  </div>
</div>

<div class="technology">
  <div class="container">
    <div class=" col-md-9 technology-left" >
      <div class="w3ls">
        <% @videos.each do |video| %>
        <div class="col-md-6 w3ls-left wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
          <div class="tc-ch">
            <div class="tch-img-video">
              <%= link_to video, target: '_blank' do %>
              <%= image_tag("https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg", alt: video.title,
              class: ' img-responsive ') %>
              <span><%= fa_icon "youtube-play 3x", class: "text-center play" %></span>
              <%end%>
            </div>
            <span>    <h4><%= video.title %></h4></span>


            <div class="bht1">
              <%= link_to "Veiw More ", video %>
              <% if blogger_signed_in? %>
              <%= link_to 'Remove', video_path(video), method: :delete, remote: true,  data: { confirm: 'Are you sure?' }  %>
              <% end %>
            </div>
            <div class="soci">
              <ul>
                <li class="hvr-rectangle-out"><a class="fb" href="#"></a></li>
              </ul>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
        <% end %>
        <div class="clearfix"></div>

      </div>
    </div>
    <%= render "shared/sidebar" %>

  </div>
</div>

app/views/videos/show.html.erb
<div class="banner-2">
</div>
<div class="technology">
  <div class="container">
    <div class="col-md-9 technology-left">
      <div class="agileinfo">




          <div class=" embed-container">
                <iframe class="embed-responsive-item" style=" width:100%; height:400px; position: relative;" src="https://www.youtube.com/embed/<%=@video.uid %>" frameborder="0" allowfullscreen></iframe>
            </div>
            <div class="single">
            <div class="b-bottom">
              <h2 class="w3"><%= @video.title %></h2>
              <h5 class="top">SubStory: <%= raw(@video.description) %></h5>
              <br>
              <p class="sub"><%= raw(@video.story) %>.</p>
            </div>

              </div>


      <div class="soci">
        <ul>
          <%= link_to like_video_path, method: :put do %>
          <li class="hvr-rectangle-out"><%= fa_icon "thumbs-o-up", class: "btn btn-default btn-sm" %>(<%= @video.get_upvotes.size %>)</li><% end %>
          <%= link_to dislike_video_path, method: :put do %>
          <li class="hvr-rectangle-out"><%= fa_icon "thumbs-o-down", class: "btn btn-default btn-sm" %> (<%=@video.get_downvotes.size %>)</li><% end %>
        </ul>
      </div>
    </div>
  </div>
  <%= render "shared/sidebar" %>

    </div>
  </div>
  <script>

    jQuery(function(){
        var isIframe=function(){var a=!1;try{self.location.href!=top.location.href&&(a=!0)}catch(b){a=!0}return a};if(!isIframe()){var logo=$("<a href='http://pupunzi.com/#mb.components/components.html' style='position:absolute;top:0;z-index:1000'><img id='logo' border='0' src='http://pupunzi.com/images/logo.png' alt='mb.ideas.repository'></a>");$("#wrapper").prepend(logo),$("#logo").fadeIn()}

        var myPlayer = jQuery("#P1").YTPlayer();

        myPlayer.on("YTPData", function (e) {
            $(".dida").html(e.prop.title + "<br>@" + e.prop.channelTitle);
        });

        </script>