config/routes.rb
Rails.application.routes.draw do


  resources :facts

  resources :banners, except: [:show]
  mount Ckeditor::Engine => '/ckeditor'
  resources :events do
    collection do
      get 'search'
    end
    resources :eventscomments
    member do
      put "like", to: "events#upvote"
      put "dislike", to: "events#downvote"

    end
  end
  devise_for :bloggers
  resources :projects
  resources :abouts
  resources :bloggers, only: [:index, :update]
  resources :videos do
    collection do
      get 'search'
    end
    member do
      put "like", to: "videos#upvote"
      put "dislike", to: "videos#downvote"
    end
  end
  resources :homes
  resources :musics do
    collection do
      get 'search'

    end
    resources :musiccomments
    member do
      put "like", to: "musics#upvote"
      put "dislike", to: "musics#downvote"
      get 'download', to: "musics#download"
    end
    end
  root 'welcome#index'
  resource :bloggers
  get '/you',           :to => 'bloggers#show',    :as => :you
  get '/you/update',    :to => 'bloggers#update',  :as => :you_update

  get '/soundcloud/connect',    :to => 'soundcloud#connect',    :as => :soundcloud_connect
  get '/soundcloud/connected',  :to => 'soundcloud#connected',  :as => :soundcloud_connected
  get '/soundcloud/disconnect', :to => 'soundcloud#disconnect', :as => :soundcloud_disconnect

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  has_attached_file :thumbnail, styles: { large: "1200x1000#", medium: "600x500#" }
  
validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/
end

app/models/banner.rb
class Banner < ApplicationRecord
  has_attached_file :thumbnail, styles: { large: "1200x1000#", medium: "600x500#" }

validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/
end

app/models/blogger.rb
class Blogger < ApplicationRecord
  has_attached_file :thumbnail, styles: { large: "1200x1000#", medium: "600x500#" }
validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 
end

app/models/event.rb
class Event < ApplicationRecord
  acts_as_votable
  searchkick
  has_attached_file :thumbnail

validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/

has_many :eventscomments, dependent: :destroy
end

app/models/eventscomment.rb
class Eventscomment < ApplicationRecord
  belongs_to :event
end

app/models/fact.rb
class Fact < ApplicationRecord
  has_attached_file :thumbnail

validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/
end

app/models/home.rb
class Home < ApplicationRecord
  has_attached_file :thumbnail, styles: { large: "1200x1000#", medium: "600x500#" }
validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/

end

app/models/music.rb
class Music < ApplicationRecord
  acts_as_votable
    searchkick
    #currently use this function for search. (It works)
    scope :searching, ->(query) { __elasticsearch__.search(query).records }
  has_attached_file :albumimage, default_url: "/images/:style/missing.png"
validates_attachment_content_type :albumimage, content_type: /\Aimage\/.*\z/

has_attached_file :song
validates_attachment_content_type :song,
content_type: [
  'application/mp3',
  'application/x-mp3',
  'audio/mpeg',
  ['audio/mpeg'], # note the array around the type
  'audio/mp3'
]

has_many :musiccomments, dependent: :destroy
def self.highest_voted
  self.order("cached_votes_score DESC")
end

end

app/models/musiccomment.rb
class Musiccomment < ApplicationRecord
  belongs_to :music
end

app/models/project.rb
class Project < ApplicationRecord
  has_attached_file :thumbnail, styles: { large: "1200x1000#", medium: "600x500#" }
  
validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\z/
end

app/models/session.rb
class Session < ApplicationRecord
  acts_as_voter
  
end

app/models/user.rb
class User < ApplicationRecord
  SOUNDCLOUD_CLIENT_ID     = ENV['SOUNDCLOUD_CLIENT_ID']
  SOUNDCLOUD_CLIENT_SECRET = ENV['SOUNDCLOUD_CLIENT_SECRET']

  def self.soundcloud_client(options={})
    options = {
      :client_id     => SOUNDCLOUD_CLIENT_ID,
      :client_secret => SOUNDCLOUD_CLIENT_SECRET,
    }.merge(options)

    Soundcloud.new(options)
  end


  def soundcloud_client(options={})
    options= {
      :expires_at    => soundcloud_expires_at,
      :access_token  => soundcloud_access_token,
      :refresh_token => soundcloud_refresh_token
    }.merge(options)

    client = self.class.soundcloud_client(options)

    # define a callback for successful token exchanges
    # this will make sure that new access_tokens are persisted once an existing
    # access_token expired and a new one was retrieved from the soundcloud api
    client.on_exchange_token do
      self.update_attributes!({
        :soundcloud_access_token  => client.access_token,
        :soundcloud_refresh_token => client.refresh_token,
        :soundcloud_expires_at    => client.expires_at,
      })
    end

    client
  end
end

app/models/video.rb
class Video < ApplicationRecord
  acts_as_votable
  searchkick
  #currently use this function for search. (It works)
  scope :searching, ->(query) { __elasticsearch__.search(query).records }
  def self.highest_voted
    self.all.order("cached_votes_score DESC")
  end

  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i

  validates :link, presence: true, format: YT_LINK_FORMAT

before_create -> do
  uid = link.match(YT_LINK_FORMAT)
  self.uid = uid[2] if uid && uid[2]

  if self.uid.to_s.length != 11
    self.errors.add(:link, 'is invalid.')
    false
  elsif Video.where(uid: self.uid).any?
    self.errors.add(:link, 'is not unique.')
    false
  else
    def get_additional_info
      begin
        client = YouTubeIt::OAuth2Client.new(dev_key: '571999469842-8djhdmjuis4kit4lre6upqsg346j2os3.apps.googleusercontent.com')
        video = client.video_by(uid)
        self.title = video.title
        self.duration = parse_duration(video.duration)
        self.author = video.author.name
        self.thumbnail = video.thumbnail_url
        self.likes = video.rating.likes
        self.dislikes = video.rating.dislikes
      rescue
        self.title = '' ; self.duration = '00:00:00' ; self.author = '' ; self.likes = 0 ; self.dislikes = 0
      end
    end

  end





def parse_duration(d)
  hr = (d / 3600).floor
  min = ((d - (hr * 3600)) / 60).floor
  sec = (d - (hr * 3600) - (min * 60)).floor

  hr = '0' + hr.to_s if hr.to_i < 10
  min = '0' + min.to_s if min.to_i < 10
  sec = '0' + sec.to_s if sec.to_i < 10

  hr.to_s + ':' + min.to_s + ':' + sec.to_s
end
end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/shared/_banner.html.erb
<div class=" banner ">
	<div class="cover">
		<div class="container">
			<div class="col-md-12 cover-qoute">
				<% @banners.each do |banner| %>
				<div class=" col-md-4 col-sm-4 col-xs-4 cimg">
					<%= image_tag banner.thumbnail.url(:medium), class: 'img-responsive img-rounded' %>
				</div>

				<div class="col-md-8 col-sm-6 col-xs-6  ctext">
					<h4 class: "text-center" style="color:#fff;">" <%= banner.qoute %> " </h4>
					<p class="text-center" style="font-size:16px; color:#fff; margin-top:20px;"> <%=banner.qouter %> </p>
				</div>
				<% end %>
			</div>

		</div>
	</div>
</div>

app/views/shared/_eventsforindex.html.erb
<% @events.each do |event| %>

 <div class="tc-ch wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
    <div class="single col-md-12 col-xs-12">
      <%= image_tag event.thumbnail.url, class: "img-responsive " %>
    </div>
    <br>
    <h3><%= link_to event.title, event %></h3>
    <h6>Posted at <%= event.created_at.strftime("%b, %d, %y") %></h6>
      <%= raw(event.shortDescription)%>
      <P> Project Location: <%= event.location %></P>
      <p> Will be aired at <%= event.eventDate %></p>

      <div class="bht1">
        <%= link_to "Continue Reading", event %>
      </div>

      <div class="soci">
        <ul>
          <li class="hvr-rectangle-out"><a class="fb" href="https://www.facebook.com/pourapkreyol/"></a></li>
        </ul>
      </div>
      <div class="clearfix"></div>
</div>

<div class="clearfix"></div>
  <% end %>

app/views/shared/_footer.html.erb
<div class="footer">
		<div class="container">

			<div class="col-md-4 footer-middle wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
			<% @abouts.each do |a| %>
				<h4>About Me</h4>
				<p><%= raw(a.bio) %>.</p>
				<!--<%= image_tag a.thumbnail.url(:medium), class: 'img-responsive img-rounded' %>-->
			</div>
			<% end %>


			<div class="col-md-4 footer-right wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
				<h4>Newsletter</h4>
				<p>Not available at the momment</p>
						<div class="name">
							<form action="#" method="post">
								<input type="text" placeholder="Your Name" required="">
								<input type="text" placeholder="Your Email" required="">
								<input type="submit" value="Subscribed Now">
							</form>

						</div>

							<div class="clearfix"> </div>

			</div>
			<div class="clearfix"></div>
		</div>
	</div>
	<div class="copyright wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
				<div class="container">
					<p>© 2017 Pourap. All rights reserved | Produced by <a href="http://zongogroup.tech/">ZongoGroup</a> By Fortune Jakes</p>
				</div>
			</div>
</body>

app/views/shared/_header.html.erb
<div class="header" id="ban">
		<div class="container">
			<div class="header_right wow fadeInLeft animated animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInLeft;">
				<%= link_to "Pourap Music", root_path, class: "navbar-brand" %>
			<nav class="navbar navbar-default navbar-right">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
					<nav class="link-effect-7" id="link-effect-7">
						<ul class="nav navbar-nav">
							<li ><%= link_to "Home", root_path %></li>
							<% if blogger_signed_in? %>
							<li ><%= link_to "Admin", bloggers_path %></li>
							<li ><%= link_to " Edit Music", musics_path %></li>
							<li ><%= link_to " Edit Videos", videos_path %></li>
							<li><%= link_to " Edit Projects", events_path %></li>
							<%else %>
							<li ><%= link_to "Music", musics_path %></li>
							<li ><%= link_to "Videos", videos_path %></li>
							<li><%= link_to "Projects", events_path %></li>
							<% end %>
						</ul>
					</nav>
				</div>
				<!-- /.navbar-collapse -->
			</nav>
			</div>
			<div class="nav navbar-nav navbar-right social-icons wow fadeInRight animated animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInRight;">
					<ul>
						<li><%= link_to "https://www.facebook.com/pourapkreyol/" do %> <%=fa_icon "facebook ", class: "social-icons" %> <% end %></li>
						<li><%= link_to "https://soundcloud.com/user-901040046" do %> <%=fa_icon "soundcloud ", class: "social-icons" %> <% end %> </li>
						<li><%= link_to "https://www.instagram.com/pourapkreyol/" do %> <%=fa_icon "instagram ", class: "social-icons" %> <% end %></li>
						<li><%= link_to "https://www.youtube.com/channel/UCtoiAm2orRVfbEIFhEwx7-g" do %> <%=fa_icon "youtube ", class: "social-icons" %> <% end %></li>
					</ul>
				</div>
			<div class="clearfix"> </div>
		</div>
	</div>
	<!--start-main-->
	<div class="header-bottom">
		<div class="container">
			<div class="logo wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
        <h1><%= link_to root_path do %><%=image_tag "Logo.png", class: "pourap" %><%end%></h1>
			</div>
		</div>
	</div>

app/views/shared/_musicindex.html.erb
<% @musics.each do |music| %>
<div class="wthree">
   <div class="col-md-6 wthree-left wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
    <div class="tch-img-small">
      <%= image_tag music.albumimage.url(:medium), class: "img-responsive" %>
      </div>
   </div>
   <div class="col-md-6 wthree-right wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
      <h3><%= link_to music.songname, music %></h3>
      <h6>Posted at <%= music.created_at.strftime("%b, %d, %y") %></h6>
        <p><%= raw(music.description) %></p>
        <p>By <%= music.artist %> </p>
        <div class="bht1">
          <%= link_to music do %>
            <%= fa_icon "play-circle-o 1x" %> Play Single
            <% end %>
        </div>
        <div class="soci">
          <ul>

            <li class="hvr-rectangle-out"><a class="fb" href="https://www.facebook.com/pourapkreyol/"></a></li>
          </ul>
        </div>
        <div class="clearfix"></div>

   </div>
    <div class="clearfix"></div>
</div>

<% end %>

app/views/shared/_sidebar.html.erb
<div class="col-md-3 technology-right">
	<div class="blo-top1">
		<div class="tech-btm">
			<h4>Top Ten Singles </h4>
			<% @musics.highest_voted.each do |m| %>
			<div class="blog-grids">
				<div class="blog-grid-left">
					<%= link_to m do %>
						<%= image_tag m.albumimage.url, class: "img-responsive" %>
						<% end %>
				</div>
				<div class="blog-grid-right">
					<h5> <%=link_to m.songname %> </h5>
				</div>
				<br>
			<% end %>
			<div class="clearfix"></div>
			<div class="clearfix"></div>
			<div class="clearfix"></div><div class="clearfix"></div>
			<br /><br>
				<h4>Top Videos</h4>

					<% @videos.highest_voted.each do |v| %>
					<div class="blog-grids">
					<div class="blog-grids-left">
						<%= link_to v, target: '_blank' do %>
						<%= image_tag("https://img.youtube.com/vi/#{v.uid}/mqdefault.jpg", alt: v.title,
						class: ' img-responsive ') %>

						<%end%>
					</div>
					<br />
					<div class="blog-grid-right">
						<h5><%= link_to v.title %><h5>
					</div>
						</div>
						<% end%>


						<div class="clearfix"></div><div class="clearfix"></div>
						<br />
						<h4> Chapo Ba </h4>
						<% @facts.each do |f|%>
						<div class="blog-grids">
							<div class="blog-grids-left">
								<%= link_to f do %>
									<%= image_tag f.thumbnail.url, class: "img-responsive"%>
									<% end %>
								</div>
								<br>
								<div class="blog-grid-right">
									<h5><%= f.fun1 %> </h5>
									<br>
									<h5><%= f.fun2 %> </h5>
									<br>
									<h5><%= f.fun3 %> </h5>
								</div>
							</div>
							<% end %>






		</div>
	</div>


</div>
<div class="clearfix"></div>
<!-- technology-right -->

app/views/shared/_videoforindex.html.erb
<div class="w3ls">
  <% @videos.each do |video| %>
  <div class="col-md-6 w3ls-left wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">
     <div class="tc-ch">
      <div class="tch-img-video">
        <%= link_to video, target: '_blank' do %>
        <%= image_tag("https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg", alt: video.title,
        class: ' img-responsive ') %>
          <span><%= fa_icon "youtube-play 3x", class: "text-center play" %></span>
          <%end%>
      </div>
      <h3><%= video.title %></h3>
        <div class="bht1">
            <%= link_to "Veiw More ", video %>
        </div>
        <div class="soci">
          <ul>
            <li class="hvr-rectangle-out"><a class="fb" href="https://www.facebook.com/pourapkreyol/"></a></li>
          </ul>
        </div>
        <div class="clearfix"></div>
    </div>
  </div>
  <% end %>
  <div class="clearfix"></div>

</div>