config/routes.rb
Rails.application.routes.draw do


  resources :facts

  resources :banners, except: [:show]
  mount Ckeditor::Engine => '/ckeditor'
  resources :events do
    collection do
      get 'search'
    end
    resources :eventscomments
    member do
      put "like", to: "events#upvote"
      put "dislike", to: "events#downvote"

    end
  end
  devise_for :bloggers
  resources :projects
  resources :abouts
  resources :bloggers, only: [:index, :update]
  resources :videos do
    collection do
      get 'search'
    end
    member do
      put "like", to: "videos#upvote"
      put "dislike", to: "videos#downvote"
    end
  end
  resources :homes
  resources :musics do
    collection do
      get 'search'

    end
    resources :musiccomments
    member do
      put "like", to: "musics#upvote"
      put "dislike", to: "musics#downvote"
      get 'download', to: "musics#download"
    end
    end
  root 'welcome#index'
  resource :bloggers
  get '/you',           :to => 'bloggers#show',    :as => :you
  get '/you/update',    :to => 'bloggers#update',  :as => :you_update

  get '/soundcloud/connect',    :to => 'soundcloud#connect',    :as => :soundcloud_connect
  get '/soundcloud/connected',  :to => 'soundcloud#connected',  :as => :soundcloud_connected
  get '/soundcloud/disconnect', :to => 'soundcloud#disconnect', :as => :soundcloud_disconnect

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/music.rb
class Music < ApplicationRecord
  acts_as_votable
    searchkick
    #currently use this function for search. (It works)
    scope :searching, ->(query) { __elasticsearch__.search(query).records }
  has_attached_file :albumimage, default_url: "/images/:style/missing.png"
validates_attachment_content_type :albumimage, content_type: /\Aimage\/.*\z/

has_attached_file :song
validates_attachment_content_type :song,
content_type: [
  'application/mp3',
  'application/x-mp3',
  'audio/mpeg',
  ['audio/mpeg'], # note the array around the type
  'audio/mp3'
]

has_many :musiccomments, dependent: :destroy
def self.highest_voted
  self.order("cached_votes_score DESC")
end

end

app/controllers/musics_controller.rb
  class MusicsController < ApplicationController
    before_action :authenticate_blogger!, except: [:index, :show, :search]
    layout "bloggers", except: [:index, :show, :search]
    before_action :set_music, only:[:show, :edit, :upvote, :downvote, :update, :destroy]
    def search
      if params[:search].present?
        @musics = Music.search(params[:search])
        @musics = Music.highest_voted.limit(10)
        @videos = Video.highest_voted.limit(10)
        @facts = Fact.all.order('created_at DESC').limit(1)
        @abouts = About.all.order("created_at DESC").limit(1)

        #@tracks = current_user.soundcloud_client.get("/me/tracks", :limit => 5)
        #@me     = current_user.soundcloud_client.get("/me")

      else
        @musics = Music.all.order("created_at DESC")
      end
    end
    def index
        
      @musics = Music.all.order("created_at DESC")
      @musics = Music.highest_voted.limit(10)
      @videos = Video.highest_voted.limit(10)
      @facts = Fact.all.order('created_at DESC').limit(1)
      @abouts = About.all.order("created_at DESC").limit(1)
    end

    def show
      @videos = Video.highest_voted.all.limit(10)
      @musics = Music.highest_voted.all.limit(10)
      @facts = Fact.all.order('created_at DESC').limit(1)
      @abouts = About.all.limit(1)
      #@tracks = current_user.soundcloud_client.get("/me/tracks", :limit => 5)
      #@me     = current_user.soundcloud_client.get("/me")

    end

    def new
      @music = Music.new
    end

    def create
      @music = Music.new(music_params)

      if @music.save
        redirect_to @music
        flash = { success: "Congratulations!! Created Successfully", error: "Action Not Successfull." }
      else
        render 'new'
      end
    end

    def edit

    end

    def update
      res = current_user.soundcloud_client.put("/me", :user => {:description => params[:description]})
      redirect_to :action => :show
      if @music.update
        redirect_to @music
        flash = { success: "Congratulations!! Updated Successfully", error: "Action Not Successfull." }

      else
        render 'edit'
      end
    end


    def destroy
      @music.destroy
      redirect_to musics_url
      flash = { success: "Congratulations!! Deleted Successfully", error: "Action Not Successfull." }

    end

    def upvote
      @music = Music.find(params[:id])
      session[:voting_id] = request.remote_ip
      voter = Session.find_or_create_by(ip: session[:voting_id])
      voter.likes @music
      redirect_to :back
    end

    def downvote
      @music = Music.find(params[:id])
      session[:voting_id] = request.remote_ip
      voter = Session.find_or_create_by(ip: session[:voting_id])
      voter.dislikes @music
      redirect_to :back
    end



    def download
      @music = Music.find(params[:id])

      extension = File.extname(@music.song_file_name)
      send_data open("#{@music.song.expiring_url(10000, :original)}").read, filename: "#{@music.songname}_#{@music.id}#{extension}", type: @music.song_content_type, x_sendfile: true
    end



    private
    def music_params
      params.require(:music).permit(:songname, :description, :albumimage, :artist, :discography, :published, :subtitle, :song)
    end

    def set_music
      @music = Music.find(params[:id])
    end

  end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/_form.html.erb
<%= simple_form_for(@music, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>
<div class="form-group">
  <%= f.input :albumimage, as: :file, label: "Album Image", class: "form-control" %>
</div>

<div class="form-group">
  <%= f.input :songname, label: "Song Title", class: "form-control" %>
</div>

<div class="form-group">
  <%= f.input :artist, label: "Song artist", class: "form-control" %>
</div>

<div class="form-group">
  <%= f.input :subtitle, label: "Song SubStory", class: "form-control" %>
</div>

<div class="form-group">
  <%= f.input :description, label: "Song Discription for home page", class: "form-control", as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' } } %>
</div>

<div class="form-group">
  <%= f.input :discography, label: "Song discography", class: "form-control", as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' } } %>
</div>

<div class="form-group">
  <%= f.input :published, label: "Release Date" %>
</div>

<div class="form-group">
  <%= f.input :song, as: :file, label: "Upload Yor Song.mp3", class: "form-control" %>
</div>

<div class="form-group">
  <%= f.submit :submit, class: "btn btn-success" %>
</div>

<% end %>

app/views/musics/edit.html.erb
<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Music Upload Edit</h1>
			</div>
		</div><!--/.row-->


		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">Add Songs and Etc </div>
					<div class="panel-body">
						<div class="col-md-6 col-md-offset-3">

              <%= render "form", music: :@music %>


              </div>
              </div>
              </div>
              </div>
              </div>

app/views/musics/index.html.erb
<div class="banner-1">
  <div class="container">
    <div class="col-md-12">
      <div class="wrapper top">
      <%= form_tag search_musics_path, method: :get, role: "search" do  %>
        <%=text_field_tag :search, params[:search], class: "search1", placeholder: "Search" %>
        <%=submit_tag "", name:nil, label: false,  class: "submit1"  %>
        <% end %>
      </div>
      </div>
    </div>
  </div>

<div class="technology">
<div class="container">
  <div class="col-md-9 technology-left">
    <div class="music">
      <div class="latest">
          <h2 class="w3">MUSIC</h2>
          <% @musics.each do |music| %>
          <div class="tip-grids">
            <div class="col-md-6 tip-grid">
                <%= link_to music do %>
              <figure class="effect-julia">
                <%= image_tag music.albumimage.url, class: "img-responsive" %>
              </figure>
              <% end %>
            </div>
            <div class="col-md-6 tip-grid-right">
              <div class="tip-gd-left">
                  <h4><%= music.songname %></h4>
                <p><%= raw(music.subtitle) %></p>
          
              </div>
            </div>
            <div class="bht1">
              <%= link_to "Play & Download ", music %>
            </div>
            <div class="soci">
              <ul>

                <%= link_to like_music_path(music), method: :put do %>
                <li class="hvr-rectangle-out"><%= fa_icon "thumbs-o-up", class: " btn-sm" %>(<%= music.get_upvotes.size %>)</li><% end %>
                <%= link_to dislike_music_path(music), method: :put do %>
                <li class="hvr-rectangle-out"><%= fa_icon "thumbs-o-down", class: " btn-sm" %>(<%=music.get_downvotes.size %>)</li><% end %>
                <li class="hvr-rectangle-out"><a class="fb"  href="https://www.facebook.com/pourapkreyol/"></a></li>
                <% if blogger_signed_in? %>
                <li class="hvr-rectangle-out" >
                <%= link_to music_path(music), method: :delete, remote: true,  data: { confirm: 'Are you sure?' } do  %>
                <%= fa_icon "trash-o", class: "btn-sm" %>
                    <% end %>
              </li>
                <% end %>

              </ul>
            </div>
            <div class="clearfix"></div>
          </div>
          <% end %>
      </div>
    </div>
  </div>
  <%= render "shared/sidebar" %>
</div>
</div>

app/views/musics/new.html.erb
<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Music Upload</h1>
			</div>
		</div><!--/.row-->


		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">Add Songs and Etc </div>
					<div class="panel-body">
						<div class="col-md-6 col-md-offset-3">

              <%= render "form", music: :@music %>


              </div>
              </div>
              </div>
              </div>
              </div>

app/views/musics/search.html.erb
<div class="banner-1">
  <div class="container">
    <div class="col-md-12">
      <div class="wrapper top">
      <%= form_tag search_musics_path, method: :get, role: "search" do  %>
        <%=text_field_tag :search, params[:search], class: "search1", placeholder: "Search" %>
        <%=submit_tag "", name:nil, label: false,  class: "submit1"  %>
        <% end %>
      </div>
      </div>
  </div>
</div>
<div class="technology">
<div class="container">
  <div class="col-md-9 technology-left">
    <div class="music">
      <div class="latest">
          <h2 class="w3">MUSIC</h2>
          <% @musics.each do |music| %>
          <div class="tip-grids">
            <div class="col-md-6 tip-grid">
                <%= link_to music do %>
              <figure class="effect-julia">
                <%= image_tag music.albumimage.url, class: "img-responsive" %>
              </figure>
              <% end %>
            </div>
            <div class="col-md-6 tip-grid-right">
              <div class="tip-gd-left">
                  <h4><%= music.songname %></h4>
                <p><%= raw(music.subtitle) %></p>
              </div>
            </div>
            <div class="bht1">
              <%= link_to "View Single ", music %>
            </div>
            <div class="soci">
              <ul>

                <%= link_to like_music_path(music), method: :put do %>
                <li class="hvr-rectangle-out"><%= fa_icon "thumbs-o-up", class: " btn-sm" %>(<%= music.get_upvotes.size %>)</li><% end %>
                <%= link_to dislike_music_path(music), method: :put do %>
                <li class="hvr-rectangle-out"><%= fa_icon "thumbs-o-down", class: " btn-sm" %>(<%=music.get_downvotes.size %>)</li><% end %>
                <li class="hvr-rectangle-out"><a class="fb" href="#"></a></li>
                <li class="hvr-rectangle-out"><a class="pin" href="#"></a></li>
                <% if blogger_signed_in? %>
                <li class="hvr-rectangle-out" >
                <%= link_to music_path(music), method: :delete, remote: true,  data: { confirm: 'Are you sure?' } do  %>
                <%= fa_icon "trash-o", class: "btn-sm" %>
                  <% end %>
              </li>
                <% end %>

              </ul>
            </div>
            <div class="clearfix"></div>
          </div>
          <% end %>
      </div>
    </div>
  </div>
  <%= render "shared/sidebar" %>
</div>
</div>

app/views/musics/show.html.erb
<div class="banner-1">
</div>
<div class="technology">
  <div class="container">
    <div class="col-md-9 technology-left">
      <div class="agileinfo">

        <h2 class="w3"><%= @music.songname %></h2>
        <div class="b-bottom">
          <div class="single">
          <div class="col-md-12 col-sm-12" >
          <%= image_tag @music.albumimage.url, class: "img-responsive" %>
        </div>
      </div>
        <div class="space"></div>
        <div class="row">
          <div class="content-container col-md-12">
            <div id="jquery_jplayer_1" class="jp-jplayer"></div>
            <div id="jp_container_1" class="jp-audio" role="application" aria-label="media player">
              <div class="jp-type-playlist">
                <div class="jp-gui jp-interface">
                  <div class="jp-controls">
                    <button class="jp-previous" role="button" tabindex="0">previous</button>
                    <button class="jp-play" role="button" tabindex="0">play</button>
                    <button class="jp-next" role="button" tabindex="0">next</button>
                    <button class="jp-stop" role="button" tabindex="0">stop</button>
                  </div>
                  <div class="jp-progress">
                    <div class="jp-seek-bar">
                      <div class="jp-play-bar"></div>
                    </div>
                  </div>
                  <div class="jp-volume-controls">
                    <button class="jp-mute" role="button" tabindex="0">mute</button>
                    <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
                    <div class="jp-volume-bar">
                      <div class="jp-volume-bar-value"></div>
                    </div>
                  </div>
                  <div class="jp-time-holder">
                    <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
                    <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
                  </div>
                  <div class="jp-toggles">
                    <button class="jp-repeat" role="button" tabindex="0">repeat</button>
                    <button class="jp-shuffle" role="button" tabindex="0">shuffle</button>
                  </div>
                </div>
                <!-- FlashPlayer Fallback-->
                <div class="jp-no-solution">
                  <span>Update Required</span>
                  To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                </div>
                <!-- /FlashPlayer Fallback-->
              </div>
            </div>
          </div>
        </div>
          <br>
          <div class="text-center col-md-12">
            <div class="col-md-6 col-md-offset-4">
              <%= button_to download_music_path, :method => :get, class: " btn btn-lg btn-warning" do %>
              <%= fa_icon "download 2x" %> Download Single
              <% end %>

              <div class="soci">
                <ul>
                <%= link_to like_music_path, method: :put do %>
                <li><%= fa_icon "thumbs-o-up", class: "btn btn-default btn-sm" %><%= @music.get_upvotes.size %></li><% end %>
                <%= link_to dislike_music_path, method: :put do %>
                <li ><%= fa_icon "thumbs-o-down", class: "btn btn-default btn-sm" %> <%=@music.get_downvotes.size %></li><% end %>
              </ul>
            </div>
            </div>
          </div>
          <br>

            <h5 class="top">SubStory: <%= raw(@music.subtitle) %></h5>
            <br>
            <p class="sub"><%= raw(@music.description) %>.</p>


            <p class"sub" >Discogrphy:<%= raw(@music.discography) %> </p>
            <p class="sub"> Published At<%= @music.published %> </p>
          </div>


        <%= render @music.musiccomments %>
        <%= render 'musiccomments/form' %>
      </div>
    </div>
      <%= render "shared/sidebar" %>
    </div>
  </div>












      <script type="text/javascript">
      //<![CDATA[
      $(document).ready(function(){

        $("#jquery_jplayer_1").jPlayer({
          ready: function (event) {
            $(this).jPlayer("setMedia", {
              title: "<%= @music.songname %>",
              mp3: "<%= @music.song.url %>",
              m4a: "<%= @music.song.url %>",
              oga: "<%= @music.song.url %>"

            });
          },
          swfPath: "/js",
          supplied: "m4a, mp3",
          wmode: "window",
          useStateClassSkin: true,
          autoBlur: false,
          smoothPlayBar: true,
          keyEnabled: true,
          remainingDuration: true,
          toggleDuration: true
        });
      });
      //]]>
      </script>